# Generated by Django 2.2.4 on 2020-08-09 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('expirationMonth', models.IntegerField()),
                ('expirationYear', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=4)),
                ('paytype', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('create_datetime', models.DateTimeField(default=datetime.datetime(2020, 8, 9, 18, 34, 19, 800437))),
            ],
        ),
    ]
