# Generated by Django 2.2.4 on 2020-08-09 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 18, 55, 47, 208604)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Cards'),
        ),
    ]
