# Generated by Django 2.2.4 on 2020-08-10 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20200809_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 2, 45, 31, 730403, tzinfo=utc)),
        ),
    ]
